name: Add to Project

on:
  issues:
    types:
      - opened

jobs:
  add-label-to-issue:
    name: Add label to issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          script: |
            const issueTitle = context.payload.issue.title;
            const keywords = ['🔮', '📗', '✅'];
            const labels = ['epic', 'story', 'feature'];

            for (let i=0; i<3; i++) {
              if (issueTitle.indexOf(keywords[i]) > -1) {
                github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  labels: [labels[i]],
                });
                break;
              }
            }

  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/boostcampwm2023/projects/19
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
